language: cpp
compiler:
- clang
- gcc
os:
- linux
- osx
dist: xenial
addons:
  homebrew:
    packages:
    - cmake
    - eigen
    - glm
    - qt
  apt:
    packages:
    - cmake
    - libeigen3-dev
    - qt5-default
before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone https://github.com/g-truc/glm.git; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir build-glm; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd build-glm; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake ../glm; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make && make install; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ..; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf glm build-glm; fi
script:
- cmake -DTHREEDIMUTIL_BUILD_DEMOS=OFF . && make
- cmake -DTHREEDIMUTIL_BUILD_DEMOS=ON . && make
