language: cpp
matrix:
  include:
  - compiler: gcc
    os: linux
  - compiler: clang
    os: osx
dist: xenial
addons:
  homebrew:
    update: true
    packages:
    - eigen
    - qt
  apt:
    packages:
    - libeigen3-dev
    - qt5-default
script:
- cmake -DTHREEDIMUTIL_BUILD_DEMOS=OFF . && make
- cmake -DTHREEDIMUTIL_BUILD_DEMOS=ON . && make
